package ar.unrn.tp3.correo;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import ar.unrn.tp3.modelo.EnvioDeCorreo;
public class MailTrapEnvioDeCorreo implements EnvioDeCorreo{

	@Override
	public void enviarCorreo(String nombre, String correoDelEmpleado) {
		// TODO Auto-generated method stub
		// Put recipient’s address
	      //String to = "test@example.com";

	      // Put sender’s address
	      String from = "desdeJava@programaCorreos.com";
	      final String username = "3f8452d56b4195";//username generated by Mailtrap
	      final String password = "913ce7a176dcc9";//password generated by Mailtrap

	      // Paste host address from the SMTP settings tab in your Mailtrap Inbox
	      String host = "smtp.mailtrap.io";

	      Properties props = new Properties();
	      props.put("mail.smtp.auth", "true");
	      props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
	      props.put("mail.smtp.host", host);
	      props.put("mail.smtp.port", "2525");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

	      // Get the Session object.
	      Session session = Session.getInstance(props,
	         new javax.mail.Authenticator() {
	            protected PasswordAuthentication getPasswordAuthentication() {
	               return new PasswordAuthentication(username, password);
	    }
	         });

	      try {
	    // Create a default MimeMessage object.
	    Message message = new MimeMessage(session);

	    // Set From: header field
	    message.setFrom(new InternetAddress(from));

	    // Set To: header field
	    message.setRecipients(Message.RecipientType.TO,
	               InternetAddress.parse(correoDelEmpleado));

	    // Set Subject: header field
	    message.setSubject("Mensaje de cumpleaños");

	    // Put the content of your message
	    message.setText("Feliz cumpleaños "+ nombre);

	    // Send message
	    Transport.send(message);

	    System.out.println("Sent message successfully....");

	      } catch (MessagingException e) {
	         throw new RuntimeException(e);
	      }
		
	}

	@Override
	public String recuperarContenidoDeCorreo() {
		// TODO Auto-generated method stub
		return null;
	}
}

/*
 * SMTP
Host: smtp.mailtrap.io
Port: 25 or 465 or 587 or 2525
Username: 3f8452d56b4195
Password: 913ce7a176dcc9
Auth:
PLAIN, LOGIN and CRAM-MD5
TLS: Optional (STARTTLS on all ports)*/
